//
// ANFace.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import UIKit

open class ANFace {
    public var bounds: CGRect? {
        didSet {
            width = Float((bounds?.width)!)
            height = Float((bounds?.height)!)
            x = Int32((bounds?.midX)!)
            y = Int32((bounds?.midY)!)
            
        }
    }
    public var id: Int64?
    public var width: Float?
    public var height: Float?
    public var imageWidth: Int32?
    public var imageHeight: Int32?
    public var x: Int32?
    public var y: Int32?
    public var facePoints: [FacePoint]?
    public var eulerY: Float?
    public var eulerZ: Float?
    public var yaw: Float?
    public var smile: Float?
    
    public init() {
        facePoints = [FacePoint]()
    }
}
