//
// WhiteImage.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class WhiteImage: JSONEncodable {
    public var amazonGuid: String?
    public var backgroundUrl: String?
    public var id: Int64?
    public var name: String?
    public var subjectUrl: String?
    public var thumbUrl: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["amazonGuid"] = self.amazonGuid
        nillableDictionary["backgroundUrl"] = self.backgroundUrl
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["subjectUrl"] = self.subjectUrl
        nillableDictionary["thumbUrl"] = self.thumbUrl
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
